Repository intel/ai-containers, pull requests merged in 2024-09, with the labels that each got.

#358 Compare against same Python Version
  python/README.md
Labels: documentation, Review

#360 Create Container Map
  .github/release/v0.4.0.json
Labels: Review

#361 Patch Container Mapping
  .github/release/v0.4.0.json
Labels: Review

#363 Patch container mapping (2)
  .github/release/v0.4.0.json
Labels: Review

#362 Test CPU Validation Runners
  classical-ml/.actions.json
  preset/classical-ml/.actions.json
  preset/classical-ml/tests.yaml
  preset/data-analytics/.actions.json
  preset/data-analytics/tests.yaml
  python/.actions.json
Labels: github_actions, Review

#365 Gaudi OpenShift notebook container
  .github/dependabot.yml
  enterprise/redhat/openshift-ai/gaudi/demo/oneapi-sample.ipynb
  enterprise/redhat/openshift-ai/gaudi/docker/Dockerfile.rhel9.2
  enterprise/redhat/openshift-ai/gaudi/docker/Dockerfile.rhel9.4
  enterprise/redhat/openshift-ai/gaudi/docker/builder/run
  enterprise/redhat/openshift-ai/gaudi/docker/docker-compose.yaml
  enterprise/redhat/openshift-ai/gaudi/docker/install-python310.sh
  enterprise/redhat/openshift-ai/gaudi/docker/install_efa.sh
  enterprise/redhat/openshift-ai/gaudi/docker/install_packages.sh
  enterprise/redhat/openshift-ai/gaudi/docker/requirements.txt
  enterprise/redhat/openshift-ai/gaudi/docker/start-notebook.sh
  enterprise/redhat/openshift-ai/gaudi/docker/utils/process.sh
  enterprise/redhat/openshift-ai/oneapi/README.md
  enterprise/redhat/openshift-ai/oneapi/assets/step-1.png
  enterprise/redhat/openshift-ai/oneapi/assets/step-2.png
  enterprise/redhat/openshift-ai/oneapi/assets/step-3.png
  enterprise/redhat/openshift-ai/oneapi/assets/step-4.png
  enterprise/redhat/openshift-ai/oneapi/manifests/intel-optimized-ml.yaml
  enterprise/redhat/openshift-ai/oneapi/manifests/intel-optimized-pytorch.yaml
  enterprise/redhat/openshift-ai/oneapi/manifests/intel-optimized-tensorflow.yaml
Labels: Review

#378 IPEX XPU 2.3.110 support
  python/docker-compose.yaml
  pytorch/Dockerfile
  pytorch/README.md
  pytorch/docker-compose.yaml
  pytorch/notebooks/ipex-xpu.ipynb
  pytorch/serving/README.md
  pytorch/serving/torchserve-xpu-requirements.txt
  pytorch/serving/wf-store/rest-test.sh
  pytorch/tests/tests.yaml
  pytorch/xpu-requirements.txt
Labels: Review

#377 Update Dependabot Patterns
  .github/dependabot.yml
Labels: dependencies, Review

#380 update setuptools and pip to resolve trivy vulnerabilities
  pytorch/Dockerfile
  pytorch/serving/torchserve-xpu-requirements.txt
  pytorch/venv-requirements.txt
Labels: Review

#390 fix broken links
  pytorch/README.md
Labels: Review

#393 Docs for Intel Gaudi notebook container added
  enterprise/redhat/openshift-ai/gaudi/README.md
  enterprise/redhat/openshift-ai/gaudi/assets/step-3.png
  enterprise/redhat/openshift-ai/gaudi/assets/step-4.png
  enterprise/redhat/openshift-ai/gaudi/crd-sample.yaml
Labels: Review

#394 Re-Enable Weekly Test CI
  .github/workflows/weekly-test.yaml
Labels: Review

#407 Update Intel Optimized XLA Docs
  .github/dockerhub-readmes.json
  jax/README.md
Labels: Review

#415 Fix commands in Presets' Readme
  preset/README.md
Labels: Review

#396 CI build and tests added for Gaudi Notebook container
  enterprise/redhat/openshift-ai/gaudi/docker/.actions.json
  enterprise/redhat/openshift-ai/gaudi/docker/Dockerfile.rhel9.2
  enterprise/redhat/openshift-ai/gaudi/docker/docker-compose.yaml
  enterprise/redhat/openshift-ai/gaudi/docker/tests/notebook-test.sh
  enterprise/redhat/openshift-ai/gaudi/docker/tests/tests.yaml
Labels: Review

#408 Update Optimized ML Docs for 2024.7.0
  classical-ml/README.md
Labels: Review

#406 Patch Weekly Tests
  .github/workflows/weekly-test.yaml
Labels: Review

#419 Update Runner Labels and GHA Hardening
  .github/workflows/apptainer-ci.yaml
  .github/workflows/container-ci.yaml
  .github/workflows/dependency-review.yaml
  .github/workflows/dockerhub-description.yml
  .github/workflows/docs.yaml
  .github/workflows/integration-test.yaml
  .github/workflows/lint.yaml
  .github/workflows/scorecard.yaml
  .github/workflows/security-report.yaml
  .github/workflows/test-runner-ci.yaml
  .github/workflows/weekly-test.yaml
Labels: Review

#422 splitting command block
  preset/README.md
Labels: Review
