Repository intel/ai-containers, pull requests merged in 2024-07, with the labels that each got.

#187 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Review

#201 Classical ML 2024.5.0
  classical-ml/README.md
  classical-ml/docker-compose.yaml
  classical-ml/tests/tests.yaml
Labels: Review

#202 Intel Python 2024.2.0
  python/README.md
Labels: Review

#204 Use intel-ubuntu-latest label
  .github/linters/actionlint.yml
  .github/workflows/container-ci.yaml
  .github/workflows/dependency-review.yaml
  .github/workflows/dockerhub-description.yml
  .github/workflows/docs.yaml
  .github/workflows/integration-test.yaml
  .github/workflows/lint.yaml
  .github/workflows/scorecard.yaml
  .github/workflows/test-runner-ci.yaml
  .github/workflows/weekly-test.yaml
Labels: Review

#205 Update Lint Permissions
  .github/workflows/lint.yaml
Labels: Review

#206 Update labels for push events
  .github/workflows/dockerhub-description.yml
  .github/workflows/scorecard.yaml
  .github/workflows/weekly-test.yaml
Labels: Review

#212 Add Security Report Handling
  .github/workflows/security-report.yaml
Labels: github_actions, Review

#225 Apply regreSSHion mitigation
  preset/deep-learning/Dockerfile
  pytorch/Dockerfile
  tensorflow/Dockerfile
  workflows/charts/huggingface-llm/Dockerfile
Labels: Review

#214 Fix SSH port by default in multinode container
  pytorch/Dockerfile
  pytorch/README.md
  pytorch/docker-compose.yaml
  pytorch/multinode/dockerd-entrypoint.sh
  pytorch/multinode/generate_ssh_keys.sh
  pytorch/multinode/requirements.txt
  pytorch/multinode/ssh_config
  pytorch/multinode/sshd_config
Labels: Review

#224 Fix PyTorch XPU Jupyter Documentation
  pytorch/README.md
Labels: documentation, Review

#188 Deepspeed Support
  docs/scripts/matrix.py
  pytorch/Dockerfile
  pytorch/README.md
  pytorch/docker-compose.yaml
  pytorch/multinode/requirements.txt
  pytorch/tests/ipex-resnet50.py
  pytorch/tests/tests.yaml
Labels: Review

#228 Update IPEX MultiNode Docs
  pytorch/README.md
Labels: documentation, Review

#229 Update Site Headers to have an anchor link
  mkdocs.yml
  pytorch/README.md
Labels: documentation, Review

#146 Adds Huggingface GenAI container build specs into pytorch/Dockerfile and pytorch/docker-compose.yaml
  pytorch/Dockerfile
  pytorch/README.md
  pytorch/docker-compose.yaml
  pytorch/hf-genai-requirements.txt
  pytorch/tests/tests.yaml
Labels: WIP

#211 add apptainer build functionality for python
  .github/dependabot.yml
  .github/workflows/apptainer-ci.yaml
  apptainer/README.md
  apptainer/action.yml
  apptainer/python/apptainer.def
  apptainer/python/requirements.txt
Labels: github_actions, WIP

#236 Use software.repos.intel.com Conda Channel
  preset/classical-ml/Dockerfile
  preset/classical-ml/docker-compose.yaml
  preset/data-analytics/Dockerfile
  preset/data-analytics/docker-compose.yaml
  preset/deep-learning/Dockerfile
  preset/deep-learning/docker-compose.yaml
  preset/inference-optimization/docker-compose.yaml
  python/Dockerfile
  tensorflow/Dockerfile
Labels: Review

#243 Update README.md
  preset/README.md
Labels: documentation, Review

#254 Update setuptools to beyond v70
  python/requirements.txt
Labels: Review

#256 update xpu stack to resolve conda issue
  pytorch/README.md
  pytorch/docker-compose.yaml
  pytorch/tests/tests.yaml
  pytorch/xpu-requirements.txt
  test-runner/README.md
  test-runner/utils/test.py
Labels: Review

#237 Update pull_request_template.md
  .github/pull_request_template.md
Labels: Review

#259 Update labels for hfgenai container
  pytorch/docker-compose.yaml
Labels: documentation, Review

#213 Test Reporter for Container CI
  .github/workflows/integration-test.yaml
  test-runner/action.yml
  test-runner/test_runner.py
Labels: github_actions, Review

#258 Update TR Test Badge to reflect main status
  README.md
Labels: documentation, Review

#269 MLPerf readme content for intel/intel-optimized-pytorch containers
  pytorch/README.md
Labels: documentation, Review
