Repository intel/ai-containers, pull requests merged in 2024-08, with the labels that each got.

#271 torchserve 0.11.0 tests update
  pytorch/serving/README.md
  pytorch/serving/config.properties
  pytorch/serving/model-store/grpc-test.sh
  pytorch/serving/model-store/rest-test.sh
  pytorch/serving/tests.yaml
  pytorch/serving/wf-store/rest-test.sh
Labels: Review

#295 Make Integration Tests status-check dependent on merge logs job
  .github/workflows/integration-test.yaml
Labels: github_actions, Review

#255 Adding classical-ml and data-analytics presets
  .github/workflows/container-ci.yaml
  .github/workflows/integration-test.yaml
  preset/classical-ml/Dockerfile
  preset/classical-ml/docker-compose.yaml
  preset/classical-ml/requirements.txt
  preset/classical-ml/tests/scikit/kmeans.py
  preset/classical-ml/tests/scikit/test_scikit.sh
  preset/data-analytics/Dockerfile
  preset/data-analytics/docker-compose.yaml
  preset/data-analytics/requirements.txt
  preset/deep-learning/Dockerfile
  preset/deep-learning/docker-compose.yaml
  preset/deep-learning/requirements.txt
  preset/deep-learning/tests.yaml
  preset/inference-optimization/Dockerfile
  preset/inference-optimization/docker-compose.yaml
  preset/inference-optimization/requirements.txt
  preset/inference-optimization/tests.yaml
Labels: WIP

#293 Remove keyless sources from pytorch xpu
  pytorch/Dockerfile
Labels: bug, Review

#306 Token Authentication enabled and tested for Torchserve workflow
  pytorch/serving/config.properties
  workflows/charts/torchserve/README.md
  workflows/charts/torchserve/templates/NOTES.txt
  workflows/charts/torchserve/templates/deploy.yaml
  workflows/charts/torchserve/values.yaml
Labels: Review

#305 update ipex layers to 2.1.40-xpu
  pytorch/Dockerfile
  pytorch/README.md
  pytorch/docker-compose.yaml
  pytorch/tests/tests.yaml
  pytorch/xpu-requirements.txt
Labels: Review

#312 update pytorch cpu whl index
  pytorch/requirements.txt
  pytorch/serving/build-kfs.sh
  pytorch/serving/patch.yaml
Labels: Review

#313 Update Intel Optimized ML Docs
  classical-ml/README.md
  classical-ml/docker-compose.yaml
  classical-ml/tests/tests.yaml
Labels: documentation, Review

#283 Add TGI on Intel Chart
  workflows/charts/tgi/.helmignore
  workflows/charts/tgi/Chart.yaml
  workflows/charts/tgi/README.md
  workflows/charts/tgi/README.md.gotmpl
  workflows/charts/tgi/templates/NOTES.txt
  workflows/charts/tgi/templates/_helpers.tpl
  workflows/charts/tgi/templates/deploy.yaml
  workflows/charts/tgi/templates/ingress.yaml
  workflows/charts/tgi/templates/secret.yaml
  workflows/charts/tgi/templates/service.yaml
  workflows/charts/tgi/templates/tests/test-connection.yaml
  workflows/charts/tgi/values.yaml
Labels: enhancement, Review

#329 Correct TM&B
  CONTRIBUTING.md
  README.md
  classical-ml/README.md
  mkdocs.yml
  python/README.md
  pytorch/README.md
  pytorch/serving/README.md
  tensorflow/README.md
  workflows/README.md
  workflows/charts/huggingface-llm/README.md
  workflows/charts/torchserve/Chart.yaml
  workflows/charts/torchserve/README.md
  workflows/charts/torchserve/README.md.gotmpl
Labels: documentation, Review

#330 Open Up XPU Conda Reqs
  pytorch/xpu-requirements.txt
  tensorflow/xpu-requirements.txt
Labels: dependencies, Review

#307 Add Perf Sample Example Section
  python/README.md
Labels: documentation, Review
